server:
  port: 8083
  servlet:
    session:
      timeout: 10s

spring:
  datasource:
    username: root
    password: 520...ng
    url: jdbc:mysql://127.0.0.1/sample-web?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name: com.alibaba.druid.proxy.DruidDriver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.ng.demo.model

logging:
   level:
     com.ng.demo.dao: trace